// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherSmartObjectLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UTetherSmartObjectLibrary::IsSmartObjectApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::IsSmartObjectApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherSmartObjectLibrary::GetLastSmartObjectError()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetLastSmartObjectError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("Smart Object API requires Unreal Engine 5.7+");
}

FTetherSmartObjectCreateResult UTetherSmartObjectLibrary::CreateSmartObjectDefinition(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::CreateSmartObjectDefinition requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectCreateResult{};
}

FTetherSmartObjectDefinitionInfo UTetherSmartObjectLibrary::GetSmartObjectDefinitionInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectDefinitionInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectDefinitionInfo{};
}

FTetherSmartObjectValidationResult UTetherSmartObjectLibrary::ValidateSmartObjectDefinition(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ValidateSmartObjectDefinition requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectValidationResult{};
}

TArray<FTetherSmartObjectPropertyInfo> UTetherSmartObjectLibrary::ListSmartObjectDefinitionProperties(const FString& AssetPath, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectDefinitionProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectPropertyInfo>{};
}

FTetherSmartObjectPropertyResult UTetherSmartObjectLibrary::GetSmartObjectDefinitionProperty(const FString& AssetPath, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectDefinitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectPropertyResult{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectDefinitionProperty(const FString& AssetPath, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectDefinitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherSmartObjectLibrary::GetSmartObjectTagQueryJson(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectTagQueryJson requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectTagQueryJson(const FString& AssetPath, const FString& QueryJson, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectTagQueryJson requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectTags(const FString& AssetPath, const TArray<FString>& Tags, const FString& SlotId, const FString& TagSet)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectTags requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectTagPolicies(const FString& AssetPath, const FString& UserTagsFilteringPolicy, const FString& ActivityTagsMergingPolicy)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectTagPolicies requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectSlotInfo> UTetherSmartObjectLibrary::ListSmartObjectSlots(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectSlots requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectSlotInfo>{};
}

FString UTetherSmartObjectLibrary::AddSmartObjectSlot(const FString& AssetPath, const FString& Name, const FVector& Offset, const FRotator& Rotation, bool bEnabled, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::AddSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherSmartObjectLibrary::DuplicateSmartObjectSlot(const FString& AssetPath, const FString& SourceSlotId, const FString& NewName, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::DuplicateSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::RemoveSmartObjectSlot(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RemoveSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::MoveSmartObjectSlot(const FString& AssetPath, const FString& SlotId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::MoveSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectPropertyInfo> UTetherSmartObjectLibrary::ListSmartObjectSlotProperties(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectSlotProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectPropertyInfo>{};
}

FTetherSmartObjectPropertyResult UTetherSmartObjectLibrary::GetSmartObjectSlotProperty(const FString& AssetPath, const FString& SlotId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectSlotProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectPropertyResult{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectSlotProperty(const FString& AssetPath, const FString& SlotId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectSlotProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectTypeInfo> UTetherSmartObjectLibrary::ListSmartObjectBehaviorTypes()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectBehaviorTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectTypeInfo>{};
}

TArray<FTetherSmartObjectBehaviorInfo> UTetherSmartObjectLibrary::ListSmartObjectBehaviorDefinitions(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectBehaviorDefinitions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectBehaviorInfo>{};
}

FString UTetherSmartObjectLibrary::AddSmartObjectBehaviorDefinition(const FString& AssetPath, const FString& BehaviorClassPath, const FString& SlotId, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::AddSmartObjectBehaviorDefinition requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::RemoveSmartObjectBehaviorDefinition(const FString& AssetPath, const FString& BehaviorObjectPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RemoveSmartObjectBehaviorDefinition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::MoveSmartObjectBehaviorDefinition(const FString& AssetPath, const FString& BehaviorObjectPath, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::MoveSmartObjectBehaviorDefinition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectPropertyInfo> UTetherSmartObjectLibrary::ListSmartObjectBehaviorProperties(const FString& AssetPath, const FString& BehaviorObjectPath, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectBehaviorProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectPropertyInfo>{};
}

FTetherSmartObjectPropertyResult UTetherSmartObjectLibrary::GetSmartObjectBehaviorProperty(const FString& AssetPath, const FString& BehaviorObjectPath, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectBehaviorProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectPropertyResult{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectBehaviorProperty(const FString& AssetPath, const FString& BehaviorObjectPath, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectBehaviorProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectTypeInfo> UTetherSmartObjectLibrary::ListSmartObjectDefinitionDataTypes(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectDefinitionDataTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectTypeInfo>{};
}

TArray<FTetherSmartObjectDefinitionDataInfo> UTetherSmartObjectLibrary::ListSmartObjectDefinitionData(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectDefinitionDataInfo>{};
}

FString UTetherSmartObjectLibrary::AddSmartObjectDefinitionData(const FString& AssetPath, const FString& StructTypePath, const FString& SlotId, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::AddSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::RemoveSmartObjectDefinitionData(const FString& AssetPath, const FString& DataId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RemoveSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::MoveSmartObjectDefinitionData(const FString& AssetPath, const FString& DataId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::MoveSmartObjectDefinitionData requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectPropertyInfo> UTetherSmartObjectLibrary::ListSmartObjectDefinitionDataProperties(const FString& AssetPath, const FString& DataId, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectDefinitionDataProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectPropertyInfo>{};
}

FTetherSmartObjectPropertyResult UTetherSmartObjectLibrary::GetSmartObjectDefinitionDataProperty(const FString& AssetPath, const FString& DataId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectDefinitionDataProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectPropertyResult{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectDefinitionDataProperty(const FString& AssetPath, const FString& DataId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectDefinitionDataProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectTypeInfo> UTetherSmartObjectLibrary::ListSmartObjectWorldConditionTypes(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectWorldConditionTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectTypeInfo>{};
}

TArray<FTetherSmartObjectWorldConditionInfo> UTetherSmartObjectLibrary::ListSmartObjectWorldConditions(const FString& AssetPath, const FString& SlotId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectWorldConditions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectWorldConditionInfo>{};
}

int32 UTetherSmartObjectLibrary::AddSmartObjectWorldCondition(const FString& AssetPath, const FString& ConditionStructPath, const FString& SlotId, const FString& Operator, int32 ExpressionDepth, bool bInvert, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::AddSmartObjectWorldCondition requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherSmartObjectLibrary::RemoveSmartObjectWorldCondition(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RemoveSmartObjectWorldCondition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::MoveSmartObjectWorldCondition(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::MoveSmartObjectWorldCondition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectWorldConditionExpression(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, const FString& Operator, int32 ExpressionDepth, bool bInvert)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectWorldConditionExpression requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectPropertyInfo> UTetherSmartObjectLibrary::ListSmartObjectWorldConditionProperties(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectWorldConditionProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectPropertyInfo>{};
}

FTetherSmartObjectPropertyResult UTetherSmartObjectLibrary::GetSmartObjectWorldConditionProperty(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectWorldConditionProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectPropertyResult{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectWorldConditionProperty(const FString& AssetPath, const FString& SlotId, int32 ConditionIndex, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectWorldConditionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectParameterInfo> UTetherSmartObjectLibrary::ListSmartObjectParameters(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectParameters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectParameterInfo>{};
}

FString UTetherSmartObjectLibrary::AddSmartObjectParameter(const FString& AssetPath, const FString& Name, const FString& Type, const FString& DefaultValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::AddSmartObjectParameter requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::RemoveSmartObjectParameter(const FString& AssetPath, const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RemoveSmartObjectParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::RenameSmartObjectParameter(const FString& AssetPath, const FString& OldName, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RenameSmartObjectParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectParameterValue(const FString& AssetPath, const FString& Name, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectParameterValue requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectBindableStructInfo> UTetherSmartObjectLibrary::ListSmartObjectBindableStructs(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectBindableStructs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectBindableStructInfo>{};
}

TArray<FTetherSmartObjectBindingInfo> UTetherSmartObjectLibrary::ListSmartObjectBindings(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectBindings requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectBindingInfo>{};
}

bool UTetherSmartObjectLibrary::AddSmartObjectBinding(const FString& AssetPath, const FString& SourceId, const FString& SourcePath, const FString& TargetId, const FString& TargetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::AddSmartObjectBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::RemoveSmartObjectBinding(const FString& AssetPath, const FString& TargetId, const FString& TargetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RemoveSmartObjectBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectComponentInfo> UTetherSmartObjectLibrary::ListSmartObjectComponents(bool bPIEOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectComponents requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectComponentInfo>{};
}

FTetherSmartObjectComponentInfo UTetherSmartObjectLibrary::GetSmartObjectComponentInfo(const FString& ComponentPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::GetSmartObjectComponentInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectComponentInfo{};
}

FString UTetherSmartObjectLibrary::AddSmartObjectComponent(const FString& ActorPath, const FString& DefinitionAssetPath, const FString& ComponentName, bool bCanBePartOfCollection, bool bRegisterWithSubsystem)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::AddSmartObjectComponent requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::RemoveSmartObjectComponent(const FString& ComponentPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::RemoveSmartObjectComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectComponentDefinition(const FString& ComponentPath, const FString& DefinitionAssetPath, bool bRegisterWithSubsystem)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectComponentDefinition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::ControlSmartObjectComponent(const FString& ComponentPath, const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ControlSmartObjectComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectCollectionInfo> UTetherSmartObjectLibrary::ListPersistentSmartObjectCollections(bool bPIEOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListPersistentSmartObjectCollections requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectCollectionInfo>{};
}

FString UTetherSmartObjectLibrary::CreatePersistentSmartObjectCollection(const FString& ActorLabel)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::CreatePersistentSmartObjectCollection requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::DestroyPersistentSmartObjectCollection(const FString& CollectionActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::DestroyPersistentSmartObjectCollection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::ControlPersistentSmartObjectCollection(const FString& CollectionActorPath, const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ControlPersistentSmartObjectCollection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectCollectionEntryInfo> UTetherSmartObjectLibrary::ListPersistentSmartObjectCollectionEntries(const FString& CollectionActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListPersistentSmartObjectCollectionEntries requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectCollectionEntryInfo>{};
}

TArray<FTetherSmartObjectQueryResult> UTetherSmartObjectLibrary::QuerySmartObjects(const FVector& Center, const FVector& Extent, const TArray<FString>& UserTags, const TArray<FString>& ActivityTags, const TArray<FString>& BehaviorClassPaths, const FString& ActivityMatch, const FString& ClaimPriority, bool bEvaluateConditions, bool bIncludeClaimedSlots, bool bIncludeDisabledSlots, const FString& UserActorPath, bool bSortByDistance, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::QuerySmartObjects requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectQueryResult>{};
}

TArray<FTetherSmartObjectRuntimeSlotInfo> UTetherSmartObjectLibrary::ListSmartObjectRuntimeSlots(const FString& SmartObjectHandle, const FString& ComponentPath, const FString& ClaimPriority)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectRuntimeSlots requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectRuntimeSlotInfo>{};
}

FString UTetherSmartObjectLibrary::CreateRuntimeSmartObject(const FString& DefinitionAssetPath, const FTransform& Transform, const FString& OwnerActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::CreateRuntimeSmartObject requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherSmartObjectLibrary::DestroyRuntimeSmartObject(const FString& SmartObjectHandle)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::DestroyRuntimeSmartObject requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherSmartObjectClaimResult UTetherSmartObjectLibrary::ClaimSmartObjectSlot(const FString& SlotHandle, const FString& UserActorPath, const FString& ClaimPriority)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ClaimSmartObjectSlot requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectClaimResult{};
}

FTetherSmartObjectClaimResult UTetherSmartObjectLibrary::OccupySmartObjectClaim(const FString& ClaimToken, const FString& BehaviorClassPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::OccupySmartObjectClaim requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectClaimResult{};
}

bool UTetherSmartObjectLibrary::ReleaseSmartObjectClaim(const FString& ClaimToken)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ReleaseSmartObjectClaim requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherSmartObjectClaimResult> UTetherSmartObjectLibrary::ListSmartObjectClaims()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ListSmartObjectClaims requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectClaimResult>{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectRuntimeTags(const FString& Handle, const FString& Scope, const TArray<FString>& Tags, bool bReplace)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectRuntimeTags requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectRuntimeEnabled(const FString& SmartObjectHandle, bool bEnabled, const FString& ReasonTag)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectRuntimeEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SetSmartObjectRuntimeSlotEnabled(const FString& SlotHandle, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SetSmartObjectRuntimeSlotEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherSmartObjectLibrary::SendSmartObjectSlotEvent(const FString& SlotHandle, const FString& EventTag)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::SendSmartObjectSlotEvent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherSmartObjectEntranceResult UTetherSmartObjectLibrary::FindSmartObjectEntrance(const FString& SlotHandle, const FTetherSmartObjectEntranceRequest& Request)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::FindSmartObjectEntrance requires UE 5.7+ — call ignored on this engine version"));
	return FTetherSmartObjectEntranceResult{};
}

TArray<FTetherSmartObjectEntranceResult> UTetherSmartObjectLibrary::ValidateSmartObjectDefinitionEntrances(const FString& AssetPath, const FTransform& OwnerTransform, const FTetherSmartObjectEntranceRequest& Request, const FString& SkipActorPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::ValidateSmartObjectDefinitionEntrances requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherSmartObjectEntranceResult>{};
}

bool UTetherSmartObjectLibrary::DebugSmartObjectSubsystem(const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherSmartObjectLibrary::DebugSmartObjectSubsystem requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
