// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherGeometryLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

int32 UTetherGeometryLibrary::CreateDynamicMesh()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::CreateDynamicMesh requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherGeometryLibrary::ReleaseDynamicMesh(int32 Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::ReleaseDynamicMesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<int32> UTetherGeometryLibrary::ListDynamicMeshHandles()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::ListDynamicMeshHandles requires UE 5.7+ — call ignored on this engine version"));
	return TArray<int32>{};
}

bool UTetherGeometryLibrary::LoadMeshFromStaticMesh(int32 Handle, const FString& AssetPath, int32 Lod)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::LoadMeshFromStaticMesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::LoadMeshFromComponent(const FString& ActorLabel, const FString& ComponentName, int32 Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::LoadMeshFromComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherGeometryLibrary::SaveMeshToNewStaticMesh(int32 Handle, const FString& NewAssetPath, const TArray<UMaterialInterface*>& MaterialList)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::SaveMeshToNewStaticMesh requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherGeometryLibrary::SaveMeshToExistingStaticMesh(int32 Handle, const FString& ExistingAssetPath, bool bReplaceMaterials)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::SaveMeshToExistingStaticMesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherMeshInfo UTetherGeometryLibrary::GetMeshInfo(int32 Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::GetMeshInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMeshInfo{};
}

bool UTetherGeometryLibrary::MeshBoolean(int32 HandleA, int32 HandleB, const FString& Op)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshBoolean requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::MeshSmooth(int32 Handle, int32 Iterations, float Strength)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshSmooth requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::MeshDecimate(int32 Handle, int32 TargetTris)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshDecimate requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::RecomputeNormalsAndTangents(int32 Handle, float AngleThresholdDeg)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::RecomputeNormalsAndTangents requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::AppendBox(int32 Handle, FVector Origin, FVector Size)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::AppendBox requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::AppendSphere(int32 Handle, FVector Origin, float Radius, int32 ResolutionUV)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::AppendSphere requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::AppendCylinder(int32 Handle, FVector Origin, float Radius, float Height, int32 RadialSegments)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::AppendCylinder requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::AppendCone(int32 Handle, FVector Origin, float BaseRadius, float Height, int32 RadialSegments)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::AppendCone requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::MeshTransform(int32 Handle, FTransform Transform)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshTransform requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::MeshUniformRemesh(int32 Handle, int32 TargetTriCount)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshUniformRemesh requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::MeshDisplaceFromTexture(int32 Handle, const FString& TexturePath, float Magnitude, int32 UVChannel)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshDisplaceFromTexture requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::MeshVoxelMerge(const TArray<int32>& Handles, float CellSizeCm)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshVoxelMerge requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::MeshUVUnwrap(int32 Handle, const FString& Method)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::MeshUVUnwrap requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UTetherGeometryLibrary::SelectByNormalDirection(int32 Handle, FVector Normal, float MaxAngleDeg)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::SelectByNormalDirection requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherGeometryLibrary::ReleaseSelection(int32 SelectionId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::ReleaseSelection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<int32> UTetherGeometryLibrary::ListSelections()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::ListSelections requires UE 5.7+ — call ignored on this engine version"));
	return TArray<int32>{};
}

bool UTetherGeometryLibrary::ExtrudeSelection(int32 Handle, int32 SelectionId, float Distance)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::ExtrudeSelection requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherGeometryLibrary::SweepAlongSpline(int32 Handle, const TArray<FVector2D>& ProfileXY, const FString& ActorLabel, const FString& ComponentName, int32 NumPathSamples)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::SweepAlongSpline requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherGeometryLibrary::BakeNormalsToTexture(int32 Handle, const FString& NewTexturePath, int32 Resolution)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::BakeNormalsToTexture requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherGeometryLibrary::BakeOcclusionToVertexColor(int32 Handle, int32 OcclusionRays)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherGeometryLibrary::BakeOcclusionToVertexColor requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
