// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherNiagaraLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UTetherNiagaraLibrary::IsNiagaraApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::IsNiagaraApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherNiagaraLibrary::GetLastNiagaraError()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::GetLastNiagaraError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("Niagara authoring API requires Unreal Engine 5.7+");
}

TArray<FTetherNiagaraTemplateInfo> UTetherNiagaraLibrary::ListNiagaraTemplates(const FString& AssetType, const FString& Query, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraTemplates requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraTemplateInfo>{};
}

TArray<FTetherNiagaraScriptInfo> UTetherNiagaraLibrary::ListNiagaraScripts(const FString& Usage, const FString& Query, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraScripts requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraScriptInfo>{};
}

FTetherNiagaraScriptInfo UTetherNiagaraLibrary::GetNiagaraScriptInfo(const FString& ScriptPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::GetNiagaraScriptInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraScriptInfo{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::CreateNiagaraSystem(const FString& AssetPath, const FString& TemplateSystemPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CreateNiagaraSystem requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::CreateNiagaraEmitter(const FString& AssetPath, const FString& TemplateEmitterPath, bool bAddDefaultModulesAndRenderer, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CreateNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::CreateNiagaraSystemFromRecipe(const FString& AssetPath, const FTetherNiagaraSystemRecipe& Recipe, bool bCompile, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CreateNiagaraSystemFromRecipe requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::DeleteNiagaraAsset(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::DeleteNiagaraAsset requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraSystemInfo UTetherNiagaraLibrary::GetNiagaraSystemInfo(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::GetNiagaraSystemInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraSystemInfo{};
}

TArray<FTetherNiagaraEmitterInfo> UTetherNiagaraLibrary::ListNiagaraEmitters(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraEmitters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraEmitterInfo>{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::AddNiagaraEmitter(const FString& SystemPath, const FString& Name, const FString& EmitterAssetOrTemplatePath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::AddNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::DuplicateNiagaraEmitter(const FString& SystemPath, const FString& EmitterIdOrName, const FString& NewName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::DuplicateNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

bool UTetherNiagaraLibrary::RemoveNiagaraEmitter(const FString& SystemPath, const FString& EmitterIdOrName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RemoveNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::RenameNiagaraEmitter(const FString& SystemPath, const FString& EmitterIdOrName, const FString& NewName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RenameNiagaraEmitter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraEmitterEnabled(const FString& SystemPath, const FString& EmitterIdOrName, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraEmitterEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraEmitterProperties(const FString& SystemPath, const FString& EmitterIdOrName, bool bLocalSpace, const FString& SimTarget, bool bDeterministic, int32 RandomSeed, bool bUseFixedBounds, const FBox& FixedBounds, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraEmitterProperties requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherNiagaraModuleInfo> UTetherNiagaraLibrary::ListNiagaraModules(const FString& SystemPath, const FString& EmitterIdOrName, const FString& Usage)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraModules requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraModuleInfo>{};
}

TArray<FTetherNiagaraModuleInputInfo> UTetherNiagaraLibrary::ListNiagaraModuleInputs(const FString& SystemPath, const FString& ModuleId, bool bIncludeHidden)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraModuleInputs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraModuleInputInfo>{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::AddNiagaraModule(const FString& SystemPath, const FString& EmitterIdOrName, const FString& Usage, const FString& ScriptPath, const FString& SuggestedName, int32 Index, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::AddNiagaraModule requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

bool UTetherNiagaraLibrary::RemoveNiagaraModule(const FString& SystemPath, const FString& ModuleId, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RemoveNiagaraModule requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraModuleEnabled(const FString& SystemPath, const FString& ModuleId, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraModuleEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraModuleInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraModuleInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::LinkNiagaraModuleInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& LinkedParameter, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::LinkNiagaraModuleInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::SetNiagaraModuleDynamicInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& DynamicInputScriptPath, const FString& SuggestedName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraModuleDynamicInput requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

bool UTetherNiagaraLibrary::SetNiagaraModuleObjectInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& ObjectPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraModuleObjectInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::SetNiagaraModuleDataInterfaceInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& DataInterfaceClassPath, const TArray<FTetherNiagaraPropertyValue>& Properties, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraModuleDataInterfaceInput requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

TArray<FTetherNiagaraPropertyInfo> UTetherNiagaraLibrary::ListNiagaraModuleInputObjectProperties(const FString& SystemPath, const FString& ModuleId, const FString& InputName, bool bIncludeAdvanced)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraModuleInputObjectProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraPropertyInfo>{};
}

bool UTetherNiagaraLibrary::SetNiagaraModuleInputObjectProperty(const FString& SystemPath, const FString& ModuleId, const FString& InputName, const FString& PropertyName, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraModuleInputObjectProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::ResetNiagaraModuleInput(const FString& SystemPath, const FString& ModuleId, const FString& InputName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ResetNiagaraModuleInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::AddNiagaraParameterAssignment(const FString& SystemPath, const FString& EmitterIdOrName, const FString& Usage, const FString& ParameterName, const FString& Type, const FString& Value, int32 Index, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::AddNiagaraParameterAssignment requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

TArray<FTetherNiagaraParameterInfo> UTetherNiagaraLibrary::ListNiagaraUserParameters(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraUserParameters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraParameterInfo>{};
}

bool UTetherNiagaraLibrary::AddNiagaraUserParameter(const FString& SystemPath, const FString& Name, const FString& Type, const FString& DefaultValue, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::AddNiagaraUserParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraUserParameterDefault(const FString& SystemPath, const FString& Name, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraUserParameterDefault requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::RenameNiagaraUserParameter(const FString& SystemPath, const FString& OldName, const FString& NewName, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RenameNiagaraUserParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::RemoveNiagaraUserParameter(const FString& SystemPath, const FString& Name, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RemoveNiagaraUserParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherNiagaraRendererInfo> UTetherNiagaraLibrary::ListNiagaraRenderers(const FString& SystemPath, const FString& EmitterIdOrName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraRenderers requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraRendererInfo>{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::AddNiagaraRenderer(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererType, const FString& Name, const FString& MaterialPath, const FString& MeshPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::AddNiagaraRenderer requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

bool UTetherNiagaraLibrary::RemoveNiagaraRenderer(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RemoveNiagaraRenderer requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraRendererEnabled(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, bool bEnabled, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraRendererEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherNiagaraPropertyInfo> UTetherNiagaraLibrary::ListNiagaraRendererProperties(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, bool bIncludeAdvanced)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraRendererProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraPropertyInfo>{};
}

FString UTetherNiagaraLibrary::GetNiagaraRendererProperty(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& PropertyName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::GetNiagaraRendererProperty requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherNiagaraLibrary::SetNiagaraRendererProperty(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& PropertyName, const FString& Value, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraRendererProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraRendererMaterial(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& MaterialPath, int32 MaterialIndex, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraRendererMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraRendererBinding(const FString& SystemPath, const FString& EmitterIdOrName, const FString& RendererId, const FString& BindingProperty, const FString& VariableName, const FString& SourceMode, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraRendererBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraSystemWarmup(const FString& SystemPath, float WarmupTime, float TickDelta, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraSystemWarmup requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraSystemFixedBounds(const FString& SystemPath, bool bEnabled, const FBox& Bounds, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraSystemFixedBounds requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraSystemEffectType(const FString& SystemPath, const FString& EffectTypePath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraSystemEffectType requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherNiagaraCompileResult UTetherNiagaraLibrary::CompileNiagaraSystem(const FString& SystemPath, bool bForce, bool bWaitForGpuShaders, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CompileNiagaraSystem requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraCompileResult{};
}

FTetherNiagaraCompileResult UTetherNiagaraLibrary::GetNiagaraCompileDiagnostics(const FString& SystemPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::GetNiagaraCompileDiagnostics requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraCompileResult{};
}

FTetherNiagaraAuditResult UTetherNiagaraLibrary::ValidateNiagaraSystem(const FString& SystemPath, bool bCheckMaterials, bool bCheckBounds, int32 MaxEmitters, int32 MaxRenderersPerEmitter, int32 MaxModulesPerEmitter)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ValidateNiagaraSystem requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraAuditResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::CreateWeaponTrailEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& Color, float Width, float Lifetime, float SpawnRate, bool bLocalSpace, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CreateWeaponTrailEffect requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::CreateSparkEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& Color, int32 Count, float Speed, float Lifetime, float Gravity, bool bCollision, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CreateSparkEffect requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::CreateExplosionEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& CoreColor, float Scale, float Duration, int32 DebrisCount, bool bShockwave, bool bLight, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CreateExplosionEffect requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::CreateDissolveEffect(const FString& AssetPath, const FString& Style, const FString& MaterialPath, const FLinearColor& Color, int32 Count, float Duration, float Radius, const FVector& Direction, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::CreateDissolveEffect requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

FTetherNiagaraOperationResult UTetherNiagaraLibrary::SpawnNiagaraPreview(const FString& SystemPath, const FTransform& Transform, bool bAutoActivate, bool bResetOnChange)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SpawnNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraOperationResult{};
}

TArray<FTetherNiagaraPreviewInfo> UTetherNiagaraLibrary::ListNiagaraPreviews()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ListNiagaraPreviews requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherNiagaraPreviewInfo>{};
}

FTetherNiagaraPreviewInfo UTetherNiagaraLibrary::GetNiagaraPreviewInfo(const FString& Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::GetNiagaraPreviewInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherNiagaraPreviewInfo{};
}

bool UTetherNiagaraLibrary::AdvanceNiagaraPreview(const FString& Handle, float Seconds, float TickDelta)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::AdvanceNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraPreviewTransform(const FString& Handle, const FTransform& Transform, bool bTeleport)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraPreviewTransform requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::SetNiagaraPreviewVariable(const FString& Handle, const FString& Name, const FString& Type, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::SetNiagaraPreviewVariable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::ControlNiagaraPreview(const FString& Handle, const FString& Action)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::ControlNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherNiagaraLibrary::RemoveNiagaraPreview(const FString& Handle)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RemoveNiagaraPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UTetherNiagaraLibrary::RemoveAllNiagaraPreviews()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherNiagaraLibrary::RemoveAllNiagaraPreviews requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
