// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherPoseSearchLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FTetherPSSInfo UTetherPoseSearchLibrary::GetSchemaInfo(const FString& SchemaPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::GetSchemaInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherPSSInfo{};
}

TArray<FTetherPSSChannel> UTetherPoseSearchLibrary::ListSchemaChannels(const FString& SchemaPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::ListSchemaChannels requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherPSSChannel>{};
}

FTetherPSSCrashingLegsChannelResult UTetherPoseSearchLibrary::SetCrashingLegsChannel(const FString& SchemaPath, const FString& LeftThighBone, const FString& RightThighBone, const FString& LeftFootBone, const FString& RightFootBone, float Weight, float AllowedTolerance, bool bUseContinuingPose)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::SetCrashingLegsChannel requires UE 5.7+ — call ignored on this engine version"));
	return FTetherPSSCrashingLegsChannelResult{};
}

FTetherPSDInfo UTetherPoseSearchLibrary::GetDatabaseInfo(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::GetDatabaseInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherPSDInfo{};
}

TArray<FTetherPSDAnimEntry> UTetherPoseSearchLibrary::ListDatabaseAnimations(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::ListDatabaseAnimations requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherPSDAnimEntry>{};
}

TArray<FString> UTetherPoseSearchLibrary::FindDatabasesUsingAnimation(const FString& AnimationAssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::FindDatabasesUsingAnimation requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

FTetherPSDAddResult UTetherPoseSearchLibrary::AddAnimationToDatabase(const FString& DatabasePath, const FString& AnimationAssetPath, float SamplingRangeMin, float SamplingRangeMax, const FString& MirrorOption, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::AddAnimationToDatabase requires UE 5.7+ — call ignored on this engine version"));
	return FTetherPSDAddResult{};
}

FTetherPSDAddResult UTetherPoseSearchLibrary::AddBlendSpaceToDatabase(const FString& DatabasePath, const FString& BlendSpacePath, int32 HSamples, int32 VSamples, bool bUseGridForSampling, bool bUseSingleSample, float BlendParamX, float BlendParamY, float SamplingRangeMin, float SamplingRangeMax, const FString& MirrorOption, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::AddBlendSpaceToDatabase requires UE 5.7+ — call ignored on this engine version"));
	return FTetherPSDAddResult{};
}

bool UTetherPoseSearchLibrary::RemoveDatabaseAnimationAt(const FString& DatabasePath, int32 Index)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::RemoveDatabaseAnimationAt requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UTetherPoseSearchLibrary::RemoveDatabaseAnimationByAsset(const FString& DatabasePath, const FString& AnimationAssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::RemoveDatabaseAnimationByAsset requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherPoseSearchLibrary::ClearDatabaseAnimations(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::ClearDatabaseAnimations requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherPoseSearchLibrary::SetDatabaseAnimationEnabled(const FString& DatabasePath, int32 Index, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::SetDatabaseAnimationEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherPoseSearchLibrary::SetDatabaseAnimationSamplingRange(const FString& DatabasePath, int32 Index, float SamplingRangeMin, float SamplingRangeMax)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::SetDatabaseAnimationSamplingRange requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherPoseSearchLibrary::SetDatabaseAnimationMirrorOption(const FString& DatabasePath, int32 Index, const FString& MirrorOption)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::SetDatabaseAnimationMirrorOption requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherPoseSearchLibrary::SetDatabaseBlendSpaceSampling(const FString& DatabasePath, int32 Index, int32 HSamples, int32 VSamples, bool bUseGridForSampling, bool bUseSingleSample, float BlendParamX, float BlendParamY)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::SetDatabaseBlendSpaceSampling requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherPoseSearchLibrary::RequestAsyncBuildIndex(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::RequestAsyncBuildIndex requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherPoseSearchLibrary::IsIndexReady(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::IsIndexReady requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherPoseSearchLibrary::GetIndexStatus(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::GetIndexStatus requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherPoseSearchLibrary::InvalidateIndex(const FString& DatabasePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPoseSearchLibrary::InvalidateIndex requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
