// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherMaterialLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FTetherMaterialInstanceInfo UTetherMaterialLibrary::GetMaterialInstanceParameters(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialInstanceParameters requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialInstanceInfo{};
}

FTetherMaterialLayerStack UTetherMaterialLibrary::GetMaterialInstanceLayerStack(const FString& MaterialInstancePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialInstanceLayerStack requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialLayerStack{};
}

FTetherMaterialLayerStackOpResult UTetherMaterialLibrary::SetMaterialInstanceLayerStack(const FString& MaterialInstancePath, const TArray<FTetherMaterialLayerEntry>& Layers)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SetMaterialInstanceLayerStack requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialLayerStackOpResult{};
}

FTetherMaterialLayerStackOpResult UTetherMaterialLibrary::CopyMaterialInstanceLayerStack(const FString& SourceMaterialInstancePath, const FString& DestinationMaterialInstancePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::CopyMaterialInstanceLayerStack requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialLayerStackOpResult{};
}

FTetherMaterialInfo UTetherMaterialLibrary::GetMaterialInfo(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialInfo{};
}

TArray<FTetherMaterialFunctionSummary> UTetherMaterialLibrary::ListMaterialFunctions(const FString& PathPrefix, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ListMaterialFunctions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherMaterialFunctionSummary>{};
}

FTetherMaterialFunctionInfo UTetherMaterialLibrary::GetMaterialFunction(const FString& FunctionPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialFunction requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialFunctionInfo{};
}

FTetherMaterialInstanceChain UTetherMaterialLibrary::ListMaterialInstanceChain(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ListMaterialInstanceChain requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialInstanceChain{};
}

FTetherMaterialParameterCollectionInfo UTetherMaterialLibrary::GetMaterialParameterCollection(const FString& CollectionPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialParameterCollection requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialParameterCollectionInfo{};
}

FTetherMaterialGraph UTetherMaterialLibrary::GetMaterialGraph(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialGraph requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialGraph{};
}

FTetherMaterialStats UTetherMaterialLibrary::GetMaterialStats(const FString& MaterialPath, const FString& FeatureLevel, const FString& Quality)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialStats requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialStats{};
}

TArray<FString> UTetherMaterialLibrary::GetMaterialCompileErrors(const FString& MaterialPath, const FString& FeatureLevel, const FString& Quality)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialCompileErrors requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

FTetherShaderCompileStatus UTetherMaterialLibrary::GetMaterialShaderCompileStatus(const FString& MaterialPath, const FString& FeatureLevel, const FString& Quality)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetMaterialShaderCompileStatus requires UE 5.7+ — call ignored on this engine version"));
	return FTetherShaderCompileStatus{};
}

bool UTetherMaterialLibrary::PreviewMaterial(const FString& MaterialPath, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, const FString& OutPngPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::PreviewMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::PreviewMaterialComplexity(const FString& MaterialPath, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, const FString& OutPngPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::PreviewMaterialComplexity requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherCreateAssetResult UTetherMaterialLibrary::CreateMaterial(const FString& Path, const FString& Domain, const FString& ShadingModel, const FString& BlendMode, bool bTwoSided, bool bUseMaterialAttributes)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::CreateMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FTetherCreateAssetResult{};
}

FTetherCreateAssetResult UTetherMaterialLibrary::CreateMaterialInstance(const FString& ParentPath, const FString& InstancePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::CreateMaterialInstance requires UE 5.7+ — call ignored on this engine version"));
	return FTetherCreateAssetResult{};
}

FTetherAddExpressionResult UTetherMaterialLibrary::AddMaterialExpression(const FString& MaterialPath, const FString& ExpressionClass, int32 X, int32 Y)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::AddMaterialExpression requires UE 5.7+ — call ignored on this engine version"));
	return FTetherAddExpressionResult{};
}

bool UTetherMaterialLibrary::ConnectMaterialExpressions(const FString& MaterialPath, FGuid SrcGuid, const FString& SrcOutputName, FGuid DstGuid, const FString& DstInputName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ConnectMaterialExpressions requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::DisconnectMaterialInput(const FString& MaterialPath, FGuid DstGuid, const FString& DstInputName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::DisconnectMaterialInput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::ConnectMaterialOutput(const FString& MaterialPath, FGuid SrcGuid, const FString& SrcOutputName, const FString& PropertyName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ConnectMaterialOutput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::DisconnectMaterialOutput(const FString& MaterialPath, const FString& PropertyName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::DisconnectMaterialOutput requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::DeleteMaterialExpression(const FString& MaterialPath, FGuid Guid)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::DeleteMaterialExpression requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::CompileMaterial(const FString& MaterialPath, bool bSaveAfter)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::CompileMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::SetMaterialExpressionProperty(const FString& MaterialPath, FGuid Guid, const FString& PropertyName, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SetMaterialExpressionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UTetherMaterialLibrary::SetMaterialExpressionProperties(const FString& MaterialPath, FGuid Guid, const TArray<FTetherExpressionPropSet>& Properties)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SetMaterialExpressionProperties requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

FGuid UTetherMaterialLibrary::AddMaterialComment(const FString& MaterialPath, int32 X, int32 Y, int32 Width, int32 Height, const FString& Text, FLinearColor Color)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::AddMaterialComment requires UE 5.7+ — call ignored on this engine version"));
	return FGuid{};
}

FGuid UTetherMaterialLibrary::AddMaterialReroute(const FString& MaterialPath, int32 X, int32 Y)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::AddMaterialReroute requires UE 5.7+ — call ignored on this engine version"));
	return FGuid{};
}

FTetherCreateAssetResult UTetherMaterialLibrary::CreateMaterialFunction(const FString& Path, const FString& Description, bool bExposeToLibrary, const FString& LibraryCategory)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::CreateMaterialFunction requires UE 5.7+ — call ignored on this engine version"));
	return FTetherCreateAssetResult{};
}

FTetherMaterialGraphOpResult UTetherMaterialLibrary::ApplyMaterialGraphOps(const FString& MaterialPath, const TArray<FTetherMaterialGraphOp>& Ops, bool bCompile)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ApplyMaterialGraphOps requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialGraphOpResult{};
}

FTetherMaterialGraphOpResult UTetherMaterialLibrary::ValidateMaterialGraphOps(const FString& MaterialPath, const TArray<FTetherMaterialGraphOp>& Ops)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ValidateMaterialGraphOps requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialGraphOpResult{};
}

int32 UTetherMaterialLibrary::AutoLayoutMaterialGraph(const FString& MaterialPath, int32 ColumnSpacing, int32 RowSpacing)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::AutoLayoutMaterialGraph requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

FString UTetherMaterialLibrary::SnapshotMaterialGraphJson(const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SnapshotMaterialGraphJson requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherMaterialLibrary::DiffMaterialGraphSnapshots(const FString& BeforeJson, const FString& AfterJson)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::DiffMaterialGraphSnapshots requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FTetherAddExpressionResult UTetherMaterialLibrary::AddCustomExpression(const FString& MaterialPath, int32 X, int32 Y, const TArray<FString>& InputNames, const FString& OutputType, const FString& Code, const TArray<FString>& IncludePaths, const FString& Description)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::AddCustomExpression requires UE 5.7+ — call ignored on this engine version"));
	return FTetherAddExpressionResult{};
}

TArray<FTetherShaderSnippet> UTetherMaterialLibrary::ListSharedSnippets()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ListSharedSnippets requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherShaderSnippet>{};
}

FTetherShaderSnippet UTetherMaterialLibrary::GetSharedSnippet(const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetSharedSnippet requires UE 5.7+ — call ignored on this engine version"));
	return FTetherShaderSnippet{};
}

FTetherMIParamResult UTetherMaterialLibrary::SetMIParams(const FString& MaterialInstancePath, const TArray<FTetherMIParamSet>& Params)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SetMIParams requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMIParamResult{};
}

FTetherTextureRefreshResult UTetherMaterialLibrary::RefreshTextureResource(const FString& TexturePath, bool bForceDerivedDataRebuild)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::RefreshTextureResource requires UE 5.7+ — call ignored on this engine version"));
	FTetherTextureRefreshResult Result;
	Result.Error = TEXT("Texture resource refresh requires Unreal Engine 5.7+");
	return Result;
}

bool UTetherMaterialLibrary::SetMIAndPreview(const FString& MaterialInstancePath, const TArray<FTetherMIParamSet>& Params, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, const FString& OutPngPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SetMIAndPreview requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FString> UTetherMaterialLibrary::SweepMIParams(const FString& MaterialInstancePath, const FString& ParamName, const TArray<FString>& Values, const FString& Mesh, const FString& Lighting, int32 Resolution, float CameraYawDeg, float CameraPitchDeg, float CameraDistance, int32 GridCols, const FString& OutGridPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SweepMIParams requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

FTetherMIParamResult UTetherMaterialLibrary::SetMaterialParameterCollection(const FString& CollectionPath, const TArray<FTetherMIParamSet>& Params)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SetMaterialParameterCollection requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMIParamResult{};
}

FString UTetherMaterialLibrary::DiffMIParams(const FString& PathA, const FString& PathB)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::DiffMIParams requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FTetherCreateAssetResult UTetherMaterialLibrary::CreatePostProcessMaterial(const FString& Path, const FString& BlendableLocation, bool bOutputAlpha)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::CreatePostProcessMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FTetherCreateAssetResult{};
}

TArray<FTetherPostProcessVolumeInfo> UTetherMaterialLibrary::GetPostProcessState()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::GetPostProcessState requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherPostProcessVolumeInfo>{};
}

bool UTetherMaterialLibrary::ApplyPostProcessMaterial(const FString& VolumeActor, const FString& MaterialPath, float Weight)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::ApplyPostProcessMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherMaterialLibrary::RemovePostProcessMaterial(const FString& VolumeActor, const FString& MaterialPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::RemovePostProcessMaterial requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherMaterialAnalysis UTetherMaterialLibrary::AnalyzeMaterial(const FString& MaterialPath, int32 InstructionBudget, int32 SamplerBudget)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::AnalyzeMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialAnalysis{};
}

FTetherMaterialAutoFixResult UTetherMaterialLibrary::AutoFixMaterial(const FString& MaterialPath, const TArray<FString>& Fixes, bool bSaveAfter)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::AutoFixMaterial requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialAutoFixResult{};
}

FTetherMaterialGraphOpResult UTetherMaterialLibrary::SetMaterialAttributeLayers(const FString& MaterialPath, FGuid ExpressionGuid, const TArray<UMaterialFunctionInterface*>& Layers, const TArray<UMaterialFunctionInterface*>& Blends, const TArray<FString>& LayerNames)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherMaterialLibrary::SetMaterialAttributeLayers requires UE 5.7+ — call ignored on this engine version"));
	return FTetherMaterialGraphOpResult{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
