// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherStateTreeLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UTetherStateTreeLibrary::IsStateTreeApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::IsStateTreeApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherStateTreeLibrary::GetLastStateTreeError()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::GetLastStateTreeError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("StateTree authoring API requires Unreal Engine 5.7+");
}

FTetherStateTreeCreateResult UTetherStateTreeLibrary::CreateStateTree(const FString& AssetPath, const FString& SchemaClassPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::CreateStateTree requires UE 5.7+ — call ignored on this engine version"));
	return FTetherStateTreeCreateResult{};
}

FTetherStateTreeAssetInfo UTetherStateTreeLibrary::GetStateTreeInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::GetStateTreeInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherStateTreeAssetInfo{};
}

bool UTetherStateTreeLibrary::ValidateStateTree(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ValidateStateTree requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherStateTreeCompileResult UTetherStateTreeLibrary::CompileStateTree(const FString& AssetPath, bool bRunValidation)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::CompileStateTree requires UE 5.7+ — call ignored on this engine version"));
	return FTetherStateTreeCompileResult{};
}

TArray<FTetherStateTreeStateInfo> UTetherStateTreeLibrary::ListStateTreeStates(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeStates requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeStateInfo>{};
}

FString UTetherStateTreeLibrary::AddStateTreeState(const FString& AssetPath, const FString& ParentStateId, const FString& Name, const FString& StateType, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::AddStateTreeState requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherStateTreeLibrary::RemoveStateTreeState(const FString& AssetPath, const FString& StateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::RemoveStateTreeState requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::MoveStateTreeState(const FString& AssetPath, const FString& StateId, const FString& NewParentStateId, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::MoveStateTreeState requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::SetStateTreeStateType(const FString& AssetPath, const FString& StateId, const FString& StateType)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeStateType requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherStateTreePropertyResult UTetherStateTreeLibrary::GetStateTreeStateProperty(const FString& AssetPath, const FString& StateId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::GetStateTreeStateProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherStateTreePropertyResult{};
}

bool UTetherStateTreeLibrary::SetStateTreeStateProperty(const FString& AssetPath, const FString& StateId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeStateProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::SetStateTreeLinkedState(const FString& AssetPath, const FString& StateId, const FString& LinkedStateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeLinkedState requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::SetStateTreeLinkedAsset(const FString& AssetPath, const FString& StateId, const FString& LinkedAssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeLinkedAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherStateTreeNodeTypeInfo> UTetherStateTreeLibrary::ListStateTreeNodeTypes(const FString& AssetPath, const FString& Kind, bool bIncludeDisallowed)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeNodeTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeNodeTypeInfo>{};
}

TArray<FTetherStateTreeNodeInfo> UTetherStateTreeLibrary::ListStateTreeNodes(const FString& AssetPath, const FString& Scope)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeNodes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeNodeInfo>{};
}

TArray<FTetherStateTreePropertyInfo> UTetherStateTreeLibrary::ListStateTreeNodeProperties(const FString& AssetPath, const FString& NodeId, const FString& DataSource, bool bIncludeInherited)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeNodeProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreePropertyInfo>{};
}

FString UTetherStateTreeLibrary::AddStateTreeNode(const FString& AssetPath, const FString& OwnerId, const FString& Scope, const FString& TypePath, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::AddStateTreeNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherStateTreeLibrary::RemoveStateTreeNode(const FString& AssetPath, const FString& NodeId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::RemoveStateTreeNode requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::MoveStateTreeNode(const FString& AssetPath, const FString& NodeId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::MoveStateTreeNode requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherStateTreePropertyResult UTetherStateTreeLibrary::GetStateTreeNodeProperty(const FString& AssetPath, const FString& NodeId, const FString& DataSource, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::GetStateTreeNodeProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherStateTreePropertyResult{};
}

bool UTetherStateTreeLibrary::SetStateTreeNodeProperty(const FString& AssetPath, const FString& NodeId, const FString& DataSource, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeNodeProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherStateTreeTransitionInfo> UTetherStateTreeLibrary::ListStateTreeTransitions(const FString& AssetPath, const FString& StateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeTransitions requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeTransitionInfo>{};
}

FString UTetherStateTreeLibrary::AddStateTreeTransition(const FString& AssetPath, const FString& StateId, const FString& Trigger, const FString& TargetType, const FString& TargetStateId, const FString& RequiredEventTag, int32 InsertIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::AddStateTreeTransition requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherStateTreeLibrary::RemoveStateTreeTransition(const FString& AssetPath, const FString& TransitionId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::RemoveStateTreeTransition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::MoveStateTreeTransition(const FString& AssetPath, const FString& TransitionId, int32 NewIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::MoveStateTreeTransition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherStateTreePropertyResult UTetherStateTreeLibrary::GetStateTreeTransitionProperty(const FString& AssetPath, const FString& TransitionId, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::GetStateTreeTransitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherStateTreePropertyResult{};
}

bool UTetherStateTreeLibrary::SetStateTreeTransitionProperty(const FString& AssetPath, const FString& TransitionId, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeTransitionProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::SetStateTreeTransitionTarget(const FString& AssetPath, const FString& TransitionId, const FString& TargetType, const FString& TargetStateId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeTransitionTarget requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherStateTreeBindingInfo> UTetherStateTreeLibrary::ListStateTreeBindings(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeBindings requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeBindingInfo>{};
}

TArray<FTetherStateTreeBindableStructInfo> UTetherStateTreeLibrary::ListStateTreeBindableStructs(const FString& AssetPath, const FString& TargetId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeBindableStructs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeBindableStructInfo>{};
}

bool UTetherStateTreeLibrary::AddStateTreeBinding(const FString& AssetPath, const FString& SourceId, const FString& SourcePath, const FString& TargetId, const FString& TargetPath, bool bOutputBinding)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::AddStateTreeBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::RemoveStateTreeBinding(const FString& AssetPath, const FString& TargetId, const FString& TargetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::RemoveStateTreeBinding requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UTetherStateTreeLibrary::ClearStateTreeBindingsForItem(const FString& AssetPath, const FString& ItemId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ClearStateTreeBindingsForItem requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

TArray<FTetherStateTreeParameterInfo> UTetherStateTreeLibrary::ListStateTreeParameters(const FString& AssetPath, const FString& ScopeId)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeParameters requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeParameterInfo>{};
}

FString UTetherStateTreeLibrary::AddStateTreeRootParameter(const FString& AssetPath, const FString& Name, const FString& Type, const FString& DefaultValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::AddStateTreeRootParameter requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherStateTreeLibrary::RemoveStateTreeRootParameter(const FString& AssetPath, const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::RemoveStateTreeRootParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::RenameStateTreeRootParameter(const FString& AssetPath, const FString& OldName, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::RenameStateTreeRootParameter requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::SetStateTreeParameterValue(const FString& AssetPath, const FString& ScopeId, const FString& Name, const FString& Value, bool bMarkOverridden)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeParameterValue requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherStateTreeBreakpointInfo> UTetherStateTreeLibrary::ListStateTreeBreakpoints(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeBreakpoints requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeBreakpointInfo>{};
}

bool UTetherStateTreeLibrary::SetStateTreeBreakpoint(const FString& AssetPath, const FString& ItemId, const FString& BreakpointType, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeBreakpoint requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::ClearStateTreeBreakpoints(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ClearStateTreeBreakpoints requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherStateTreeComponentInfo> UTetherStateTreeLibrary::ListStateTreeComponents(bool bPIEOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ListStateTreeComponents requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherStateTreeComponentInfo>{};
}

FTetherStateTreeComponentInfo UTetherStateTreeLibrary::GetStateTreeComponentInfo(const FString& ComponentPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::GetStateTreeComponentInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherStateTreeComponentInfo{};
}

bool UTetherStateTreeLibrary::SetStateTreeComponentAsset(const FString& ComponentPath, const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SetStateTreeComponentAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::ControlStateTreeComponent(const FString& ComponentPath, const FString& Action, const FString& Reason)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::ControlStateTreeComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherStateTreeLibrary::SendStateTreeComponentEvent(const FString& ComponentPath, const FString& EventTag, const FString& Origin)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherStateTreeLibrary::SendStateTreeComponentEvent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
