// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherRigLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

bool UTetherRigLibrary::IsRigApiAvailable()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::IsRigApiAvailable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherRigLibrary::GetLastRigError()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::GetLastRigError requires UE 5.7+ — call ignored on this engine version"));
	return TEXT("Control Rig / IK Rig authoring API requires Unreal Engine 5.7+");
}

TArray<FTetherRigTypeInfo> UTetherRigLibrary::ListRigTypes(const FString& Kind, const FString& Query, int32 MaxResults)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListRigTypes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigTypeInfo>{};
}

FTetherRigOperationResult UTetherRigLibrary::CreateControlRig(const FString& AssetPath, const FString& SourceSkeletalAssetPath, bool bModularRig, bool bImportCurves)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::CreateControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigOperationResult{};
}

FTetherControlRigInfo UTetherRigLibrary::GetControlRigInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::GetControlRigInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherControlRigInfo{};
}

TArray<FTetherRigElementInfo> UTetherRigLibrary::ListControlRigElements(const FString& AssetPath, const FString& ElementType)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListControlRigElements requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigElementInfo>{};
}

bool UTetherRigLibrary::ImportControlRigHierarchy(const FString& AssetPath, const FString& SourceSkeletalAssetPath, bool bReplaceExisting, bool bImportCurves)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ImportControlRigHierarchy requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherRigLibrary::AddControlRigBone(const FString& AssetPath, const FString& Name, const FString& ParentName, const FString& ParentType, const FTransform& Transform, bool bGlobalTransform, bool bImportedBone)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigBone requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigNull(const FString& AssetPath, const FString& Name, const FString& ParentName, const FString& ParentType, const FTransform& Transform, bool bGlobalTransform)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigNull requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigControl(const FString& AssetPath, const FString& Name, const FString& ParentName, const FString& ParentType, const FString& ControlType, const FString& InitialValue, const FTransform& OffsetTransform, const FTransform& ShapeTransform, const FString& ShapeName, const FLinearColor& ShapeColor, bool bAnimatable)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigControl requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigCurve(const FString& AssetPath, const FString& Name, float Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigCurve requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigConnector(const FString& AssetPath, const FString& Name, const FString& ConnectorType, const FString& Description, bool bOptional, bool bArray)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigConnector requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::RemoveControlRigElement(const FString& AssetPath, const FString& Name, const FString& ElementType)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveControlRigElement requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherRigLibrary::RenameControlRigElement(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RenameControlRigElement requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::ReparentControlRigElement(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& ParentName, const FString& ParentType, bool bMaintainGlobalTransform)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ReparentControlRigElement requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetControlRigElementTransform(const FString& AssetPath, const FString& Name, const FString& ElementType, const FTransform& Transform, bool bGlobalTransform, bool bInitial, bool bAffectChildren)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetControlRigElementTransform requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetControlRigControlShape(const FString& AssetPath, const FString& ControlName, const FString& ShapeName, const FLinearColor& ShapeColor, bool bVisible)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetControlRigControlShape requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::AddControlRigElementTag(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& Tag)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigElementTag requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::RemoveControlRigElementTag(const FString& AssetPath, const FString& Name, const FString& ElementType, const FString& Tag)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveControlRigElementTag requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherRigPropertyInfo> UTetherRigLibrary::ListControlRigControlProperties(const FString& AssetPath, const FString& ControlName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListControlRigControlProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigPropertyInfo>{};
}

FTetherRigPropertyResult UTetherRigLibrary::GetControlRigControlProperty(const FString& AssetPath, const FString& ControlName, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::GetControlRigControlProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigPropertyResult{};
}

bool UTetherRigLibrary::SetControlRigControlProperty(const FString& AssetPath, const FString& ControlName, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetControlRigControlProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherRigVMGraphInfo> UTetherRigLibrary::ListControlRigGraphs(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListControlRigGraphs requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigVMGraphInfo>{};
}

TArray<FTetherRigVMNodeInfo> UTetherRigLibrary::ListControlRigNodes(const FString& AssetPath, const FString& GraphName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListControlRigNodes requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigVMNodeInfo>{};
}

TArray<FTetherRigVMLinkInfo> UTetherRigLibrary::ListControlRigLinks(const FString& AssetPath, const FString& GraphName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListControlRigLinks requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigVMLinkInfo>{};
}

FString UTetherRigLibrary::AddControlRigMemberVariable(const FString& AssetPath, const FString& Name, const FString& CPPType, const FString& DefaultValue, bool bPublic, bool bReadOnly)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigMemberVariable requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::RemoveControlRigMemberVariable(const FString& AssetPath, const FString& Name)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveControlRigMemberVariable requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherRigLibrary::AddControlRigUnitNode(const FString& AssetPath, const FString& GraphName, const FString& UnitStructPath, const FString& MethodName, const FVector2D& Position, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigUnitNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigTemplateNode(const FString& AssetPath, const FString& GraphName, const FString& Notation, const FVector2D& Position, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigTemplateNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigVariableNode(const FString& AssetPath, const FString& GraphName, const FString& VariableName, const FString& CPPType, const FString& CPPTypeObjectPath, bool bGetter, const FString& DefaultValue, const FVector2D& Position, const FString& NodeName, bool bCreateMemberVariable)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigVariableNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigCommentNode(const FString& AssetPath, const FString& GraphName, const FString& CommentText, const FVector2D& Position, const FVector2D& Size, const FLinearColor& Color, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigCommentNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::AddControlRigBranchNode(const FString& AssetPath, const FString& GraphName, const FVector2D& Position, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddControlRigBranchNode requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::RemoveControlRigNode(const FString& AssetPath, const FString& GraphName, const FString& NodeName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveControlRigNode requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetControlRigNodePosition(const FString& AssetPath, const FString& GraphName, const FString& NodeName, const FVector2D& Position)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetControlRigNodePosition requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetControlRigPinDefaultValue(const FString& AssetPath, const FString& GraphName, const FString& PinPath, const FString& DefaultValue, bool bResizeArrays)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetControlRigPinDefaultValue requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::ConnectControlRigPins(const FString& AssetPath, const FString& GraphName, const FString& OutputPinPath, const FString& InputPinPath, bool bCreateCastNode)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ConnectControlRigPins requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::DisconnectControlRigPins(const FString& AssetPath, const FString& GraphName, const FString& OutputPinPath, const FString& InputPinPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::DisconnectControlRigPins requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherRigLayoutResult UTetherRigLibrary::AutoLayoutControlRigGraph(const FString& AssetPath, const FString& GraphName, float HorizontalSpacing, float VerticalSpacing)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AutoLayoutControlRigGraph requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigLayoutResult{};
}

FTetherRigValidationReport UTetherRigLibrary::CompileControlRig(const FString& AssetPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::CompileControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigValidationReport{};
}

FTetherRigValidationReport UTetherRigLibrary::ValidateControlRig(const FString& AssetPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ValidateControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigValidationReport{};
}

FTetherControlRigEvaluationResult UTetherRigLibrary::EvaluateControlRig(const FString& AssetPath, const FString& EventName, const TArray<FTetherRigNamedTransform>& InputControls)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::EvaluateControlRig requires UE 5.7+ — call ignored on this engine version"));
	return FTetherControlRigEvaluationResult{};
}

FTetherRigOperationResult UTetherRigLibrary::CreateIKRig(const FString& AssetPath, const FString& SkeletalMeshPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::CreateIKRig requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigOperationResult{};
}

FTetherIKRigInfo UTetherRigLibrary::GetIKRigInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::GetIKRigInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherIKRigInfo{};
}

TArray<FTetherIKSolverInfo> UTetherRigLibrary::ListIKRigSolvers(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRigSolvers requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherIKSolverInfo>{};
}

TArray<FTetherIKGoalInfo> UTetherRigLibrary::ListIKRigGoals(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRigGoals requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherIKGoalInfo>{};
}

TArray<FTetherIKChainInfo> UTetherRigLibrary::ListIKRigRetargetChains(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRigRetargetChains requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherIKChainInfo>{};
}

int32 UTetherRigLibrary::AddIKRigSolver(const FString& AssetPath, const FString& SolverTypePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddIKRigSolver requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherRigLibrary::RemoveIKRigSolver(const FString& AssetPath, int32 SolverIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveIKRigSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::MoveIKRigSolver(const FString& AssetPath, int32 SolverIndex, int32 TargetIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::MoveIKRigSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRigSolverEnabled(const FString& AssetPath, int32 SolverIndex, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRigSolverEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRigSolverBones(const FString& AssetPath, int32 SolverIndex, const FString& StartBone, const FString& EndBone)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRigSolverBones requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherRigLibrary::AddIKRigGoal(const FString& AssetPath, const FString& GoalName, const FString& BoneName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddIKRigGoal requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::RemoveIKRigGoal(const FString& AssetPath, const FString& GoalName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveIKRigGoal requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::ConnectIKRigGoalToSolver(const FString& AssetPath, const FString& GoalName, int32 SolverIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ConnectIKRigGoalToSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::DisconnectIKRigGoalFromSolver(const FString& AssetPath, const FString& GoalName, int32 SolverIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::DisconnectIKRigGoalFromSolver requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherRigLibrary::AddIKRigRetargetChain(const FString& AssetPath, const FString& ChainName, const FString& StartBone, const FString& EndBone, const FString& GoalName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddIKRigRetargetChain requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::RemoveIKRigRetargetChain(const FString& AssetPath, const FString& ChainName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveIKRigRetargetChain requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherRigLibrary::RenameIKRigRetargetChain(const FString& AssetPath, const FString& ChainName, const FString& NewName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RenameIKRigRetargetChain requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::SetIKRigRetargetRoot(const FString& AssetPath, const FString& RootBoneName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRigRetargetRoot requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRigBoneExcluded(const FString& AssetPath, const FString& BoneName, bool bExcluded)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRigBoneExcluded requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::ApplyIKRigAutoSetup(const FString& AssetPath, bool bRetargetDefinition, bool bFullBodyIK)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ApplyIKRigAutoSetup requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherRigPropertyInfo> UTetherRigLibrary::ListIKRigProperties(const FString& AssetPath, const FString& TargetKind, int32 SolverIndex, const FString& TargetName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRigProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigPropertyInfo>{};
}

FTetherRigPropertyResult UTetherRigLibrary::GetIKRigProperty(const FString& AssetPath, const FString& TargetKind, int32 SolverIndex, const FString& TargetName, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::GetIKRigProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigPropertyResult{};
}

bool UTetherRigLibrary::SetIKRigProperty(const FString& AssetPath, const FString& TargetKind, int32 SolverIndex, const FString& TargetName, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRigProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherRigValidationReport UTetherRigLibrary::ValidateIKRig(const FString& AssetPath, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ValidateIKRig requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigValidationReport{};
}

FTetherRigOperationResult UTetherRigLibrary::CreateIKRetargeter(const FString& AssetPath, const FString& SourceIKRigPath, const FString& TargetIKRigPath, const FString& SourcePreviewMeshPath, const FString& TargetPreviewMeshPath, bool bAddDefaultOps)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::CreateIKRetargeter requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigOperationResult{};
}

FTetherIKRetargeterInfo UTetherRigLibrary::GetIKRetargeterInfo(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::GetIKRetargeterInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherIKRetargeterInfo{};
}

bool UTetherRigLibrary::ConfigureIKRetargeterAssets(const FString& AssetPath, const FString& SourceIKRigPath, const FString& TargetIKRigPath, const FString& SourcePreviewMeshPath, const FString& TargetPreviewMeshPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ConfigureIKRetargeterAssets requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherIKRetargetOpInfo> UTetherRigLibrary::ListIKRetargetOps(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRetargetOps requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherIKRetargetOpInfo>{};
}

int32 UTetherRigLibrary::AddIKRetargetOp(const FString& AssetPath, const FString& OpTypePath, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddIKRetargetOp requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherRigLibrary::AddDefaultIKRetargetOps(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AddDefaultIKRetargetOps requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::RemoveIKRetargetOp(const FString& AssetPath, int32 OpIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveIKRetargetOp requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::MoveIKRetargetOp(const FString& AssetPath, int32 OpIndex, int32 TargetIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::MoveIKRetargetOp requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRetargetOpEnabled(const FString& AssetPath, int32 OpIndex, bool bEnabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRetargetOpEnabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRetargetOpParent(const FString& AssetPath, const FString& ChildOpName, const FString& ParentOpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRetargetOpParent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::AutoMapIKRetargetChains(const FString& AssetPath, const FString& MappingType, bool bForceRemap, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AutoMapIKRetargetChains requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRetargetChainMapping(const FString& AssetPath, const FString& TargetChainName, const FString& SourceChainName, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRetargetChainMapping requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherIKChainMappingInfo> UTetherRigLibrary::ListIKRetargetChainMappings(const FString& AssetPath, const FString& OpName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRetargetChainMappings requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherIKChainMappingInfo>{};
}

TArray<FTetherRigPropertyInfo> UTetherRigLibrary::ListIKRetargetOpProperties(const FString& AssetPath, int32 OpIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRetargetOpProperties requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherRigPropertyInfo>{};
}

FTetherRigPropertyResult UTetherRigLibrary::GetIKRetargetOpProperty(const FString& AssetPath, int32 OpIndex, const FString& PropertyPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::GetIKRetargetOpProperty requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigPropertyResult{};
}

bool UTetherRigLibrary::SetIKRetargetOpProperty(const FString& AssetPath, int32 OpIndex, const FString& PropertyPath, const FString& Value)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRetargetOpProperty requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FTetherIKRetargetPoseInfo> UTetherRigLibrary::ListIKRetargetPoses(const FString& AssetPath, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRetargetPoses requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherIKRetargetPoseInfo>{};
}

FString UTetherRigLibrary::CreateIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::CreateIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

FString UTetherRigLibrary::DuplicateIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& NewName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::DuplicateIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

bool UTetherRigLibrary::RenameIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& NewName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RenameIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::RemoveIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetCurrentIKRetargetPose(const FString& AssetPath, const FString& PoseName, const FString& Side)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetCurrentIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRetargetPoseBoneRotation(const FString& AssetPath, const FString& Side, const FString& BoneName, const FQuat& RotationOffset)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRetargetPoseBoneRotation requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetIKRetargetPoseRootOffset(const FString& AssetPath, const FString& Side, const FVector& TranslationOffset)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetIKRetargetPoseRootOffset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::ResetIKRetargetPose(const FString& AssetPath, const FString& Side, const FString& PoseName, const TArray<FString>& BoneNames)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ResetIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::AutoAlignIKRetargetPose(const FString& AssetPath, const FString& Side, const TArray<FString>& BoneNames, const FString& Method)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AutoAlignIKRetargetPose requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

TArray<FString> UTetherRigLibrary::ListIKRetargetProfiles(const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ListIKRetargetProfiles requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

bool UTetherRigLibrary::SaveCurrentIKRetargetProfile(const FString& AssetPath, const FString& ProfileName, bool bApplySourcePose, bool bApplyTargetPose, bool bForceAllIKOff)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SaveCurrentIKRetargetProfile requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::RemoveIKRetargetProfile(const FString& AssetPath, const FString& ProfileName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::RemoveIKRetargetProfile requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherRigLibrary::SetCurrentIKRetargetProfile(const FString& AssetPath, const FString& ProfileName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::SetCurrentIKRetargetProfile requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherRetargetBatchResult UTetherRigLibrary::BatchRetargetAnimations(const FString& RetargeterPath, const TArray<FString>& SourceAssetPaths, const FString& SourceMeshPath, const FString& TargetMeshPath, const FString& DestinationFolder, const FString& Search, const FString& Replace, const FString& Prefix, const FString& Suffix, bool bIncludeReferencedAssets, bool bOverwriteExisting, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::BatchRetargetAnimations requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRetargetBatchResult{};
}

FTetherRigValidationReport UTetherRigLibrary::ValidateIKRetargeter(const FString& AssetPath, bool bInitializeProcessor, bool bSave)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::ValidateIKRetargeter requires UE 5.7+ — call ignored on this engine version"));
	return FTetherRigValidationReport{};
}

FTetherAnimationQualityReport UTetherRigLibrary::AnalyzeAnimationQuality(const FString& AnimationPath, const TArray<FString>& FootBoneNames, int32 NumSamples, float ContactHeightTolerance, float FootSlideSpeedTolerance, float JointAngularDeltaToleranceDegrees, int32 MaxReportedBones)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherRigLibrary::AnalyzeAnimationQuality requires UE 5.7+ — call ignored on this engine version"));
	return FTetherAnimationQualityReport{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
