// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherPCGLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

TArray<FString> UTetherPCGLibrary::ListPCGGraphAssets(const FString& Filter, int32 Max)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::ListPCGGraphAssets requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FString>{};
}

TArray<FTetherPCGComponentEntry> UTetherPCGLibrary::ListPCGComponentsInLevel(const FString& LevelFilter, int32 Max)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::ListPCGComponentsInLevel requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherPCGComponentEntry>{};
}

FTetherPCGComponentState UTetherPCGLibrary::GetPCGComponentState(const FString& ActorLabel, const FString& ComponentName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::GetPCGComponentState requires UE 5.7+ — call ignored on this engine version"));
	return FTetherPCGComponentState{};
}

TArray<FTetherPCGOverrideEntry> UTetherPCGLibrary::GetPCGComponentOverrides(const FString& ActorLabel, const FString& ComponentName)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::GetPCGComponentOverrides requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherPCGOverrideEntry>{};
}

bool UTetherPCGLibrary::SetPCGComponentOverride(const FString& ActorLabel, const FString& ComponentName, const FString& Name, const FString& ExportedValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::SetPCGComponentOverride requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherPCGLibrary::TriggerPCGGenerate(const FString& ActorLabel, const FString& ComponentName, bool bForce)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::TriggerPCGGenerate requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherPCGWaitResult UTetherPCGLibrary::WaitForPCGGenerate(const FString& ActorLabel, const FString& ComponentName, float TimeoutSec)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::WaitForPCGGenerate requires UE 5.7+ — call ignored on this engine version"));
	return FTetherPCGWaitResult{};
}

bool UTetherPCGLibrary::CleanupPCGComponent(const FString& ActorLabel, const FString& ComponentName, bool bRemoveComponents)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherPCGLibrary::CleanupPCGComponent requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
