// Auto-generated by tools/gen_version_stubs.py — DO NOT EDIT MANUALLY.
//
// Provides 5.4 stub bodies for UFUNCTIONs whose real implementations are
// gated to UE 5.7+ in the corresponding library .cpp. On 5.7+ this entire
// file compiles to an empty TU. See docs/version-compatibility.md.

#include "TetherChooserLibrary.h"
#include "Misc/EngineVersionComparison.h"

#if UE_VERSION_OLDER_THAN(5, 7, 0)

FTetherCHTInfo UTetherChooserLibrary::GetChooserInfo(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::GetChooserInfo requires UE 5.7+ — call ignored on this engine version"));
	return FTetherCHTInfo{};
}

TArray<FTetherCHTColumn> UTetherChooserLibrary::ListChooserColumns(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::ListChooserColumns requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherCHTColumn>{};
}

TArray<FTetherCHTRow> UTetherChooserLibrary::ListChooserRows(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::ListChooserRows requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherCHTRow>{};
}

FTetherCHTRowResult UTetherChooserLibrary::GetChooserRowResult(const FString& ChooserTablePath, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::GetChooserRowResult requires UE 5.7+ — call ignored on this engine version"));
	return FTetherCHTRowResult{};
}

FString UTetherChooserLibrary::GetChooserCellRaw(const FString& ChooserTablePath, int32 ColumnIndex, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::GetChooserCellRaw requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

int32 UTetherChooserLibrary::AddChooserRow(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserRow requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::InsertChooserRow(const FString& ChooserTablePath, int32 BeforeRow)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::InsertChooserRow requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherChooserLibrary::RemoveChooserRow(const FString& ChooserTablePath, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::RemoveChooserRow requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::SetChooserRowDisabled(const FString& ChooserTablePath, int32 RowIndex, bool bDisabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserRowDisabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::SetChooserRowResultAsset(const FString& ChooserTablePath, int32 RowIndex, const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserRowResultAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::SetChooserRowResultClass(const FString& ChooserTablePath, int32 RowIndex, const FString& ClassPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserRowResultClass requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::SetChooserRowResultEvaluateChooser(const FString& ChooserTablePath, int32 RowIndex, const FString& SubChooserPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserRowResultEvaluateChooser requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::ClearChooserRowResult(const FString& ChooserTablePath, int32 RowIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::ClearChooserRowResult requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::SetChooserFallbackAsset(const FString& ChooserTablePath, const FString& AssetPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserFallbackAsset requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::ClearChooserFallback(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::ClearChooserFallback requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::SetChooserContextObjectClass(const FString& ChooserTablePath, const FString& ContextClassPath, const FString& Direction)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserContextObjectClass requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::CompileChooser(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::CompileChooser requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FString UTetherChooserLibrary::GetLastChooserError()
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::GetLastChooserError requires UE 5.7+ — call ignored on this engine version"));
	return FString{};
}

int32 UTetherChooserLibrary::AddChooserColumnByStructPath(const FString& ChooserTablePath, const FString& ColumnStructPath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnByStructPath requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnFloatRange(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnFloatRange requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnEnum(const FString& ChooserTablePath, const FString& BindingPropertyChain, const FString& EnumPath, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnEnum requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnBool(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnBool requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnObject(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnObject requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnGameplayTag(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnGameplayTag requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnRandomize(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnRandomize requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnOutputFloat(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnOutputFloat requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

int32 UTetherChooserLibrary::AddChooserColumnOutputObject(const FString& ChooserTablePath, const FString& BindingPropertyChain, int32 ContextIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::AddChooserColumnOutputObject requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherChooserLibrary::RemoveChooserColumn(const FString& ChooserTablePath, int32 ColumnIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::RemoveChooserColumn requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

int32 UTetherChooserLibrary::MoveChooserColumn(const FString& ChooserTablePath, int32 SourceIndex, int32 TargetIndex)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::MoveChooserColumn requires UE 5.7+ — call ignored on this engine version"));
	return int32{};
}

bool UTetherChooserLibrary::SetChooserColumnDisabled(const FString& ChooserTablePath, int32 ColumnIndex, bool bDisabled)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserColumnDisabled requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

bool UTetherChooserLibrary::SetChooserCellRaw(const FString& ChooserTablePath, int32 ColumnIndex, int32 RowIndex, const FString& T3DValue)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::SetChooserCellRaw requires UE 5.7+ — call ignored on this engine version"));
	return bool{};
}

FTetherCHTEvaluation UTetherChooserLibrary::EvaluateChooserWithContextObject(const FString& ChooserTablePath, const FString& ContextObjectPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::EvaluateChooserWithContextObject requires UE 5.7+ — call ignored on this engine version"));
	return FTetherCHTEvaluation{};
}

TArray<FTetherCHTRowResult> UTetherChooserLibrary::EvaluateChooserMultiWithContextObject(const FString& ChooserTablePath, const FString& ContextObjectPath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::EvaluateChooserMultiWithContextObject requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherCHTRowResult>{};
}

TArray<FTetherCHTRowResult> UTetherChooserLibrary::ListPossibleResults(const FString& ChooserTablePath)
{
	UE_LOG(LogTemp, Warning, TEXT("UTetherChooserLibrary::ListPossibleResults requires UE 5.7+ — call ignored on this engine version"));
	return TArray<FTetherCHTRowResult>{};
}

#endif // UE_VERSION_OLDER_THAN(5, 7, 0)
